# Generated by Django 3.2.7 on 2022-07-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0005_auto_20220624_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingaporeHotelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_hotel', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('hotel_room', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CountrySearch',
        ),
    ]
