# Generated by Django 3.2.7 on 2022-07-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0008_klhotellist_londonhotellist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klhotellist',
            old_name='country_hotel',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='klhotellist',
            old_name='hotel_room',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='londonhotellist',
            old_name='country_hotel',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='londonhotellist',
            old_name='hotel_room',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='singaporehotellist',
            old_name='country_hotel',
            new_name='hotel_name',
        ),
        migrations.RenameField(
            model_name='singaporehotellist',
            old_name='hotel_room',
            new_name='rating',
        ),
    ]
