# Generated by Django 3.2.7 on 2022-07-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0009_auto_20220711_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='klhotellist',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='londonhotellist',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singaporehotellist',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
