# Generated by Django 4.0.4 on 2022-05-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationsearch',
            name='country',
            field=models.CharField(choices=[('Singapore', 'Singapore'), ('London', 'London'), ('Malaysia', 'Malaysia')], default='Singapore', max_length=250),
        ),
    ]
