# Generated by Django 4.0.4 on 2022-05-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationsearch',
            name='start_date',
            field=models.DateField(default="2020-10-11"),
            preserve_default=False,
        ),
    ]
