# Generated by Django 4.0.4 on 2022-05-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0002_alter_destinationsearch_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationsearch',
            name='pax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
