# Generated by Django 4.0.4 on 2022-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0003_destinationsearch_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationsearch',
            name='pax',
            field=models.PositiveIntegerField(),
        ),
    ]
