# Generated by Django 3.2.7 on 2022-06-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0004_alter_destinationsearch_pax'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryjs', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='destinationsearch',
            name='country',
            field=models.CharField(max_length=250),
        ),
    ]
