# Generated by Django 3.2.7 on 2022-07-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0010_auto_20220711_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationsearch',
            name='country',
            field=models.CharField(choices=[('Singapore', 'Singapore'), ('London, UK', 'London, UK'), ('Kuala Lumpur, Malaysia', 'Kuala Lumpur, Malaysia')], default='Singapore', max_length=250),
        ),
    ]
