# Generated by Django 3.2.7 on 2022-07-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0013_peixuan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeiXuan',
        ),
    ]
