# Generated by Django 3.2.7 on 2022-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0014_delete_peixuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationsTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=250)),
            ],
        ),
    ]
