# Generated by Django 3.2.7 on 2022-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0015_destinationstry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationsearch',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='destinationsearch',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
