# Generated by Django 3.2.7 on 2022-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0016_auto_20220713_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DestinationsTry',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='destinationsearch',
            name='country',
            field=models.CharField(max_length=250),
        ),
    ]
