# Generated by Django 3.2.7 on 2022-07-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0017_auto_20220713_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('request', models.CharField(max_length=5000)),
                ('credit_card_no', models.PositiveIntegerField()),
                ('expiry', models.PositiveBigIntegerField()),
                ('cvv', models.PositiveIntegerField()),
                ('billing_address', models.CharField(max_length=500)),
            ],
        ),
    ]
